import { library } from '@fortawesome/fontawesome-svg-core';
import { faGoogle } from '@fortawesome/free-brands-svg-icons';
import {
  faArrowRight,
  faAt,
  faBan,
  faBars,
  faBug,
  faCheck,
  faCog,
  faComment,
  faDoorOpen,
  faEdit,
  faEllipsisV,
  faEnvelope,
  faExclamation,
  faExclamationTriangle,
  faHistory,
  faHome,
  faInfoCircle,
  faLink,
  faLock,
  faPlus,
  faRetweet,
  faSpinner,
  faTag,
  faTimes,
  faUser,
  faCheckCircle,
  faExclamationCircle
} from '@fortawesome/free-solid-svg-icons';

export default function registerIcons() {
  library.add(
    faArrowRight,
    faAt,
    faBan,
    faBars,
    faBug,
    faCheck,
    faCheckCircle,
    faCog,
    faComment,
    faDoorOpen,
    faEdit,
    faEllipsisV,
    faEnvelope,
    faExclamation,
    faExclamationCircle,
    faExclamationTriangle,
    faGoogle,
    faHistory,
    faHome,
    faInfoCircle,
    faLink,
    faLock,
    faPlus,
    faRetweet,
    faSpinner,
    faTag,
    faTimes,
    faUser
  );
}
